# -*- coding: utf-8 -*-
"""Cria a camada operacional da Ressoar no Supabase (SEU-PROJETO)
e semeia a partir do arquivo ac_*:

  listas / lead_listas (com status 0-3)     <- ac_lists / ac_contact_lists
  tags / lead_tags                          <- ac_tags / ac_contact_tags
  lead_atributos (jsonb)                    <- ac_field_values + ac_fields
  mensagens (biblioteca de emails)          <- ac_messages
  supressao (bounce)                        <- lead_listas status 3
  automacoes / automacao_passos             <- ac_automations + fluxos capturados na UI
  campanhas / envios / eventos_email / segmentos / webhooks_saida /
  eventos_sistema / automacao_execucoes     <- estruturas vazias (motor)
"""
import os
import json, os, time
import urllib.request, urllib.error

REF = os.environ["SUPABASE_PROJECT_REF"]       # veja .env.example
API = f"https://api.supabase.com/v1/projects/{REF}/database/query"
TOKEN = os.environ["SUPABASE_ACCESS_TOKEN"]        # veja .env.example


def run_sql(query):
    body = json.dumps({"query": query}).encode("utf-8")
    last_err = None
    for attempt in range(6):
        req = urllib.request.Request(API, data=body, method="POST", headers={
            "Authorization": "Bearer " + TOKEN,
            "Content-Type": "application/json",
            "User-Agent": "supabase-import/1.0",
        })
        try:
            with urllib.request.urlopen(req, timeout=180) as r:
                return json.loads(r.read().decode("utf-8") or "null")
        except urllib.error.HTTPError as e:
            detail = e.read().decode("utf-8", "replace")[:800]
            if e.code in (400, 401, 404):
                raise RuntimeError("HTTP %d: %s" % (e.code, detail))
            last_err = "HTTP %d: %s" % (e.code, detail)
        except Exception as e:
            last_err = str(e)
        time.sleep(3 * (attempt + 1))
    raise RuntimeError("falhou: %s" % last_err)


print("== 1/4 estrutura ==", flush=True)
run_sql("""
begin;
create extension if not exists citext;

-- ------- listas e tags operacionais -------
create table if not exists public.listas (
  lista_id    int primary key generated by default as identity,
  nome        text not null unique,
  descricao   text,
  created_at  timestamptz not null default now()
);
create table if not exists public.lead_listas (
  lead_fk       uuid not null references public.tabela_1_leads(lead_id) on delete cascade,
  lista_fk      int  not null references public.listas(lista_id) on delete cascade,
  status        smallint not null default 1 check (status in (0,1,2,3)),
  source        text,
  subscribed_at timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  primary key (lead_fk, lista_fk)
);
comment on column public.lead_listas.status is '0=nao confirmado, 1=ativo, 2=descadastrado, 3=bounce (compat ActiveCampaign)';
create index if not exists idx_lead_listas_lista on public.lead_listas (lista_fk, status);

create table if not exists public.tags (
  tag_id      int primary key generated by default as identity,
  nome        citext not null unique,
  descricao   text,
  created_at  timestamptz not null default now()
);
create table if not exists public.lead_tags (
  lead_fk    uuid not null references public.tabela_1_leads(lead_id) on delete cascade,
  tag_fk     int  not null references public.tags(tag_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (lead_fk, tag_fk)
);
create index if not exists idx_lead_tags_tag on public.lead_tags (tag_fk);

create table if not exists public.lead_atributos (
  lead_fk    uuid primary key references public.tabela_1_leads(lead_id) on delete cascade,
  dados      jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- ------- mensagens e campanhas -------
create table if not exists public.mensagens (
  mensagem_id  uuid primary key default gen_random_uuid(),
  origem_ac_id bigint unique,
  nome         text not null,
  from_name    text not null default '',
  from_email   text not null default '',
  reply_to     text,
  subject      text not null default '',
  preheader    text,
  html         text not null default '',
  text_body    text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create table if not exists public.mensagem_links (
  link_id     int primary key generated by default as identity,
  mensagem_fk uuid not null references public.mensagens(mensagem_id) on delete cascade,
  url         text not null,
  unique (mensagem_fk, url)
);
create table if not exists public.campanhas (
  campanha_id  uuid primary key default gen_random_uuid(),
  nome         text not null,
  mensagem_fk  uuid references public.mensagens(mensagem_id),
  status       text not null default 'draft'
               check (status in ('draft','scheduled','sending','paused','sent','cancelled')),
  segmento_fk  uuid,
  lista_ids    int[],
  scheduled_at timestamptz,
  started_at   timestamptz,
  finished_at  timestamptz,
  track_opens  boolean not null default true,
  track_clicks boolean not null default true,
  created_at   timestamptz not null default now()
);

-- ------- envios e eventos -------
create table if not exists public.envios (
  envio_id            uuid primary key default gen_random_uuid(),
  lead_fk             uuid not null references public.tabela_1_leads(lead_id),
  mensagem_fk         uuid references public.mensagens(mensagem_id),
  campanha_fk         uuid references public.campanhas(campanha_id),
  automacao_fk        uuid,
  passo_fk            uuid,
  provider            text,
  provider_message_id text,
  status              text not null default 'queued'
                      check (status in ('queued','sent','delivered','bounced','complained','failed','suppressed')),
  queued_at           timestamptz not null default now(),
  sent_at             timestamptz,
  unique (campanha_fk, lead_fk)
);
create index if not exists idx_envios_provider_msg on public.envios (provider_message_id);
create index if not exists idx_envios_queue on public.envios (status) where status = 'queued';

create table if not exists public.eventos_email (
  evento_id         bigint primary key generated by default as identity,
  envio_fk          uuid not null references public.envios(envio_id),
  lead_fk           uuid not null,
  tipo              text not null check (tipo in ('sent','delivered','deferred','open','click',
                                                 'bounce_hard','bounce_soft','complaint','unsubscribe')),
  url               text,
  provider_event_id text,
  payload           jsonb,
  occurred_at       timestamptz not null default now(),
  created_at        timestamptz not null default now()
);
create unique index if not exists uq_eventos_provider on public.eventos_email (provider_event_id)
  where provider_event_id is not null;
create index if not exists idx_eventos_envio on public.eventos_email (envio_fk, tipo);

-- ------- supressao -------
create table if not exists public.supressao (
  email           citext primary key,
  motivo          text not null check (motivo in ('hard_bounce','complaint','unsubscribe_global','manual','ac_import')),
  origem_envio_fk uuid references public.envios(envio_id),
  created_at      timestamptz not null default now()
);

-- ------- segmentos -------
create table if not exists public.segmentos (
  segmento_id uuid primary key default gen_random_uuid(),
  nome        text not null,
  definicao   jsonb not null,
  created_at  timestamptz not null default now()
);

-- ------- automacoes -------
create table if not exists public.automacoes (
  automacao_id uuid primary key default gen_random_uuid(),
  origem_ac_id bigint unique,
  nome         text not null,
  ativa        boolean not null default false,
  gatilho      jsonb,
  nota         text,
  created_at   timestamptz not null default now()
);
create table if not exists public.automacao_passos (
  passo_id     uuid primary key default gen_random_uuid(),
  automacao_fk uuid not null references public.automacoes(automacao_id) on delete cascade,
  ordem        int not null,
  tipo         text not null check (tipo in ('enviar_email','webhook','google_sheets','esperar','condicao','aplicar_tag','remover_tag','inscrever_lista','desinscrever_lista')),
  config       jsonb not null default '{}'::jsonb,
  unique (automacao_fk, ordem)
);
create table if not exists public.automacao_execucoes (
  execucao_id   uuid primary key default gen_random_uuid(),
  automacao_fk  uuid not null references public.automacoes(automacao_id) on delete cascade,
  lead_fk       uuid not null references public.tabela_1_leads(lead_id) on delete cascade,
  passo_atual   int not null default 0,
  status        text not null default 'em_andamento'
                check (status in ('em_andamento','aguardando','concluida','erro','cancelada')),
  agendado_para timestamptz,
  iniciado_em   timestamptz not null default now(),
  finalizado_em timestamptz,
  erro          text
);
create index if not exists idx_execucoes_pendentes on public.automacao_execucoes (agendado_para)
  where status in ('em_andamento','aguardando');

-- ------- eventos do sistema (outbox) e webhooks de saida -------
create table if not exists public.eventos_sistema (
  evento_id     bigint primary key generated by default as identity,
  tipo          text not null,
  lead_fk       uuid,
  payload       jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  processado_em timestamptz
);
create index if not exists idx_eventos_sistema_pend on public.eventos_sistema (evento_id)
  where processado_em is null;

create table if not exists public.webhooks_saida (
  webhook_id uuid primary key default gen_random_uuid(),
  nome       text not null,
  url        text not null,
  eventos    text[] not null,
  ativo      boolean not null default true,
  secret     text,
  created_at timestamptz not null default now()
);

-- RLS em tudo (mesma postura: acesso so via service role)
alter table public.listas enable row level security;
alter table public.lead_listas enable row level security;
alter table public.tags enable row level security;
alter table public.lead_tags enable row level security;
alter table public.lead_atributos enable row level security;
alter table public.mensagens enable row level security;
alter table public.mensagem_links enable row level security;
alter table public.campanhas enable row level security;
alter table public.envios enable row level security;
alter table public.eventos_email enable row level security;
alter table public.supressao enable row level security;
alter table public.segmentos enable row level security;
alter table public.automacoes enable row level security;
alter table public.automacao_passos enable row level security;
alter table public.automacao_execucoes enable row level security;
alter table public.eventos_sistema enable row level security;
alter table public.webhooks_saida enable row level security;
commit;
""")
print("estrutura ok", flush=True)
time.sleep(1.05)

print("== 2/4 seeds de dados ==", flush=True)
run_sql("""
begin;
-- listas (mantendo os ids do AC)
insert into public.listas (lista_id, nome)
select id, name from public.ac_lists
on conflict (lista_id) do nothing;
select setval(pg_get_serial_sequence('public.listas','lista_id'), (select max(lista_id) from public.listas));

-- tags (mantendo os ids do AC)
insert into public.tags (tag_id, nome)
select id, tag from public.ac_tags
on conflict (tag_id) do nothing;
select setval(pg_get_serial_sequence('public.tags','tag_id'), (select max(tag_id) from public.tags));

-- vinculos lead x lista com status
insert into public.lead_listas (lead_fk, lista_fk, status, source)
select c.lead_fk, cl.list_id::int, cl.status, 'ac_import'
from public.ac_contact_lists cl
join public.ac_contacts c on c.id = cl.contact_id and c.lead_fk is not null
on conflict (lead_fk, lista_fk) do nothing;

-- vinculos lead x tag
insert into public.lead_tags (lead_fk, tag_fk, created_at)
select c.lead_fk, ct.tag_id::int, coalesce(min(ct.applied_at), now())
from public.ac_contact_tags ct
join public.ac_contacts c on c.id = ct.contact_id and c.lead_fk is not null
group by c.lead_fk, ct.tag_id
on conflict (lead_fk, tag_fk) do nothing;

-- atributos (campos personalizados) em jsonb
insert into public.lead_atributos (lead_fk, dados)
select c.lead_fk, jsonb_object_agg(f.title, v.value)
from public.ac_field_values v
join public.ac_contacts c on c.id = v.contact_id and c.lead_fk is not null
join public.ac_fields f on f.id = v.field_id
where v.value is not null and v.value <> ''
group by c.lead_fk
on conflict (lead_fk) do update set dados = public.lead_atributos.dados || excluded.dados;

-- biblioteca de mensagens
insert into public.mensagens (origem_ac_id, nome, from_name, from_email, reply_to, subject, preheader, html, text_body)
select id,
       coalesce(nullif(raw->>'name',''), 'AC #' || id || ' - ' || coalesce(subject,'sem assunto')),
       coalesce(raw->>'fromname',''), coalesce(raw->>'fromemail',''),
       nullif(raw->>'reply2',''), coalesce(raw->>'subject',''),
       nullif(raw->>'preheader_text',''), coalesce(raw->>'html',''), nullif(raw->>'text','')
from public.ac_messages
on conflict (origem_ac_id) do nothing;

-- supressao: bounce em qualquer lista
insert into public.supressao (email, motivo)
select distinct l.email, 'ac_import'
from public.lead_listas ll
join public.tabela_1_leads l on l.lead_id = ll.lead_fk
where ll.status = 3 and l.email is not null
on conflict (email) do nothing;

-- automacoes (nomes e status reais do AC)
insert into public.automacoes (origem_ac_id, nome, ativa)
select id, name, (raw->>'status') = '1'
from public.ac_automations
on conflict (origem_ac_id) do nothing;
commit;
""")
print("seeds ok", flush=True)
time.sleep(1.05)

print("== 3/4 fluxos das automacoes (capturados na UI do AC) ==", flush=True)
BOOST = "https://seu-integrador.exemplo.com/pn1qlr8ng826hon5fr5hn1a71i6oqn9l"
FLUXOS = {
    5:  {"gatilho": {"tipo": "lista_inscrita", "lista_id": 6},
         "passos": [("enviar_email", {"mensagem": "inscricao - live semanal", "assunto": "Inscrição confirmada"})]},
    6:  {"gatilho": {"tipo": "lista_inscrita", "lista_id": 7},
         "passos": [("webhook", {"url": BOOST, "destino": "boost.space"}),
                     ("enviar_email", {"mensagem": "Confirme a sua inscrição"})]},
    8:  {"gatilho": {"tipo": "tag_adicionada", "tag_id": 21},
         "passos": [("webhook", {"url": BOOST, "destino": "boost.space"})]},
    9:  {"gatilho": {"tipo": "tag_adicionada", "tag_id": 22},
         "passos": [("webhook", {"url": BOOST, "destino": "boost.space"})]},
    10: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 7},
         "passos": [("google_sheets", {"acao": "add_row", "nota": "no app: executar via n8n"})]},
    11: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 9},
         "passos": [("google_sheets", {"acao": "add_row", "nota": "UTM -> Sheets; no app: executar via n8n"})]},
    12: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 9},
         "passos": [("webhook", {"url": BOOST, "destino": "boost.space"}),
                     ("enviar_email", {"mensagem": "LC NOV/25 - INSCRITO NO LC", "assunto": "Finalize a sua inscrição"})]},
    13: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 11},
         "passos": [("webhook", {"url": "https://seu-n8n.com.br/webhook/b19e1a6d-abe8-4316-966f-ff0b99(TRUNCADO)", "destino": "n8n", "nota": "URL truncada na captura - confirmar no n8n"}),
                     ("enviar_email", {"mensagem": "Confirme a sua inscrição", "assunto": "Confirme a sua inscrição na live exclusiva"})]},
    14: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 12},
         "passos": [("enviar_email", {"mensagem": "LP Dez/25 - Comprou ingresso", "assunto": "Boas-vindas à Imersão Terapêutica"})]},
    16: {"gatilho": {"tipo": "lista_inscrita", "lista_id": None, "qualquer_lista": True},
         "passos": [("enviar_email", {"mensagem": "LP Dez/25 - Comprou ingresso", "assunto": "Boas-vindas à Imersão Ressonante"})]},
    17: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 15},
         "passos": [("webhook", {"url": "https://seu-n8n.com.br/webhook/(TRUNCADO)", "destino": "n8n", "nota": "URL truncada na captura"})]},
    18: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 15},
         "passos": [("google_sheets", {"acao": "add_row", "nota": "no app: executar via n8n"})]},
    21: {"gatilho": {"tipo": "tag_adicionada", "tag_id": 42},
         "passos": [("enviar_email", {"mensagem": "Confirmação de Compra - Bem-vinda", "assunto": "Sua vaga na Imersão Terapêutica está confirmada!", "origem": "Hotmart aplica a tag"})]},
    22: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 17},
         "passos": [("enviar_email", {"mensagem": "Compradora Curso Exemplo", "assunto": "Boas-vindas ao Curso Exemplo"})]},
    25: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 18},
         "passos": [("webhook", {"url": "https://seu-n8n.com.br/webhook/ht/inscrito", "destino": "n8n"})]},
    26: {"gatilho": {"tipo": "lista_inscrita", "lista_id": 6},
         "passos": [("webhook", {"url": "https://seu-n8n.com.br/webhook/livessemanais/inscrito", "destino": "n8n"})]},
}

for ac_id, fluxo in FLUXOS.items():
    gat = json.dumps(fluxo["gatilho"], ensure_ascii=False).replace("'", "''")
    run_sql("update public.automacoes set gatilho = '%s'::jsonb where origem_ac_id = %d;" % (gat, ac_id))
    for ordem, (tipo, config) in enumerate(fluxo["passos"], 1):
        cfg = json.dumps(config, ensure_ascii=False).replace("'", "''")
        run_sql("""
insert into public.automacao_passos (automacao_fk, ordem, tipo, config)
select automacao_id, %d, '%s', '%s'::jsonb from public.automacoes where origem_ac_id = %d
on conflict (automacao_fk, ordem) do nothing;""" % (ordem, tipo, cfg, ac_id))
    print("  automacao AC#%d: gatilho + %d passo(s)" % (ac_id, len(fluxo["passos"])), flush=True)
    time.sleep(0.3)

run_sql("update public.automacoes set nota = 'legado julho/2025, fluxo nao mapeado' where origem_ac_id in (2,3) and nota is null;")
run_sql("update public.automacoes set nota = 'rascunho vazio no AC' where origem_ac_id = 19 and nota is null;")

print("== 4/4 verificacao ==", flush=True)
counts = run_sql("""
select 'listas' t, count(*) n from public.listas
union all select 'lead_listas', count(*) from public.lead_listas
union all select 'tags', count(*) from public.tags
union all select 'lead_tags', count(*) from public.lead_tags
union all select 'lead_atributos', count(*) from public.lead_atributos
union all select 'mensagens', count(*) from public.mensagens
union all select 'supressao', count(*) from public.supressao
union all select 'automacoes', count(*) from public.automacoes
union all select 'automacao_passos', count(*) from public.automacao_passos
order by 1;
""")
print(json.dumps(counts, ensure_ascii=False, indent=2), flush=True)
print("== fim ==", flush=True)
